/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.InsuranceAuthority;

import Model.EcoModel;
import Model.Patient.Patient;
import Model.Patient.PatientBills;
import Model.User.User;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author devikaboddu
 */
public class InsuranceCustomerInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceCustomerInfoJPanel
     */
    JPanel userProcessContainer;
    Patient patient;
    User user;
    EcoModel ecoSystem;
    public InsuranceCustomerInfoJPanel(JPanel userProcessContainer, EcoModel business, Patient p, User account) {
        initComponents();
        this.ecoSystem = business;
        this.userProcessContainer = userProcessContainer;
        this.patient = p;
        this.user = account;
        txtpFirstName.setText(p.getpFirstName());
        txtpLastName.setText(p.getpLastName());
        txtpAddress.setText(p.getpAddress());
        txtpAge.setText(Integer.toString(p.getpAge()));
        txtpGender.setText(p.getpGender());
        txtphInsuranceID.setText(p.getpHealthInsuranceID());
        txtpNumber.setText(p.getpPhoneNo());
        txtpVerification.setText(p.getpPoliceStatus());
        try{
            String s = p.getpHealthInsuranceID().substring(3,7)+"-"+p.getpHealthInsuranceID().substring(7,9)+"-"+p.getpHealthInsuranceID().substring(9,11);
            SimpleDateFormat input =new SimpleDateFormat("yyyy-MM-dd");
            Date d = input.parse(s);
            Date today = new Date();
            s = input.format(today);
            today = input.parse(s);
            System.out.print(s + d);
            int r = d.compareTo(today);
            if(r>0){
            //System.out.print("Not Expired");
            jLabel2.setText("Valid Insurance");
            } 
            else{
                //System.out.print("Expired");
                jLabel3.setText("Insurance Expired");
            }
        }
        catch(Exception e){
            jLabel3.setText("Invalid Insurance ID");
        }
        jLabel4.setText("Bill Total: "+ecoSystem.getPatDirectory().billTotal(patient));
        populateBillTable();
    }
          private void populateBillTable() {
        DefaultTableModel model = (DefaultTableModel) table1.getModel();

        model.setRowCount(0);

        for (PatientBills b : patient.getpBills()) {

            Object[] row = new Object[7];
            row[0] = b.getName();
            row[1] = b.getOrgType();
            row[2] = b.getAmount();
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        lblpPhone = new javax.swing.JLabel();
        txtpAddress = new javax.swing.JTextField();
        lblpAddress = new javax.swing.JLabel();
        txtphInsuranceID = new javax.swing.JTextField();
        lblpHealthInsuranceID = new javax.swing.JLabel();
        txtpGender = new javax.swing.JTextField();
        lblpGender = new javax.swing.JLabel();
        txtpNumber = new javax.swing.JTextField();
        txtpFirstName = new javax.swing.JTextField();
        lblpFirstName = new javax.swing.JLabel();
        txtpAge = new javax.swing.JTextField();
        lblpAge = new javax.swing.JLabel();
        txtpLastName = new javax.swing.JTextField();
        lblpLastName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        aprvBtn = new javax.swing.JButton();
        rjctBtn = new javax.swing.JButton();
        verificationBtn = new javax.swing.JButton();
        txtpVerification = new javax.swing.JTextField();
        lblpVerification = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(9, 145, 143));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Information");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 540, 50));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1392, 10));

        table1.getTableHeader().setFont(new java.awt.Font("Trebuchet MS", 1, 16));
        table1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Name", "Organization", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 770, 350));

        lblpPhone.setBackground(new java.awt.Color(255, 255, 255));
        lblpPhone.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblpPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblpPhone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblpPhone.setText("Phone Number");
        add(lblpPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, 30));

        txtpAddress.setEditable(false);
        txtpAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpAddressActionPerformed(evt);
            }
        });
        add(txtpAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 190, 40));

        lblpAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblpAddress.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblpAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblpAddress.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblpAddress.setText("Address");
        add(lblpAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 76, 18));

        txtphInsuranceID.setEditable(false);
        txtphInsuranceID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphInsuranceIDActionPerformed(evt);
            }
        });
        add(txtphInsuranceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 190, 30));

        lblpHealthInsuranceID.setBackground(new java.awt.Color(255, 255, 255));
        lblpHealthInsuranceID.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblpHealthInsuranceID.setForeground(new java.awt.Color(255, 255, 255));
        lblpHealthInsuranceID.setText("Insurance Id");
        add(lblpHealthInsuranceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 106, -1));

        txtpGender.setEditable(false);
        add(txtpGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 190, 30));

        lblpGender.setBackground(new java.awt.Color(255, 255, 255));
        lblpGender.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblpGender.setForeground(new java.awt.Color(255, 255, 255));
        lblpGender.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblpGender.setText("Gender");
        add(lblpGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 98, 30));

        txtpNumber.setEditable(false);
        txtpNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpNumberActionPerformed(evt);
            }
        });
        add(txtpNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 190, 30));

        txtpFirstName.setEditable(false);
        add(txtpFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 166, 190, 30));

        lblpFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblpFirstName.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblpFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblpFirstName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblpFirstName.setText("First Name");
        add(lblpFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 116, -1));

        txtpAge.setEditable(false);
        txtpAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpAgeActionPerformed(evt);
            }
        });
        add(txtpAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 190, 30));

        lblpAge.setBackground(new java.awt.Color(255, 255, 255));
        lblpAge.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblpAge.setForeground(new java.awt.Color(255, 255, 255));
        lblpAge.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblpAge.setText("Age");
        add(lblpAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 50, -1));

        txtpLastName.setEditable(false);
        txtpLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpLastNameActionPerformed(evt);
            }
        });
        add(txtpLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, 30));

        lblpLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblpLastName.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblpLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblpLastName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblpLastName.setText("Last Name");
        add(lblpLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 116, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 308, 33));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(716, 284, 304, 33));

        aprvBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aprvBtn.setForeground(new java.awt.Color(0, 255, 0));
        aprvBtn.setText("Approve");
        aprvBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aprvBtnActionPerformed(evt);
            }
        });
        add(aprvBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 210, 70));

        rjctBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rjctBtn.setForeground(new java.awt.Color(255, 0, 51));
        rjctBtn.setText("Reject");
        rjctBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rjctBtnActionPerformed(evt);
            }
        });
        add(rjctBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 210, 70));

        verificationBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        verificationBtn.setForeground(new java.awt.Color(0, 51, 153));
        verificationBtn.setText("Send for Verification");
        verificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificationBtnActionPerformed(evt);
            }
        });
        add(verificationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 580, 220, 70));

        txtpVerification.setEditable(false);
        txtpVerification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpVerificationActionPerformed(evt);
            }
        });
        add(txtpVerification, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 190, 30));

        lblpVerification.setBackground(new java.awt.Color(255, 255, 255));
        lblpVerification.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblpVerification.setForeground(new java.awt.Color(255, 255, 255));
        lblpVerification.setText("Police Verification");
        add(lblpVerification, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 156, -1));

        backBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(9, 145, 143));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 120, 50));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 540, 210, 41));
    }// </editor-fold>//GEN-END:initComponents

    private void txtpAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpAddressActionPerformed

    private void txtphInsuranceIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphInsuranceIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphInsuranceIDActionPerformed

    private void txtpNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpNumberActionPerformed

    private void txtpAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpAgeActionPerformed

    private void txtpLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpLastNameActionPerformed

    private void aprvBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aprvBtnActionPerformed
        // TODO add your handling code here:
        patient.setpInsuranceStatus("Approved");
        try{
            //ecoSystem.sendEmail("hospital.aed@zohomail.com", "Approval Confirmation for "+patient.getpFirstName(), "Patient Insurance Approved Name: "+patient.getpFirstName()+" "+patient.getpLastName(), "insurance.aed@zohomail.com", "Bangbang@8899");
        }
        catch(Exception e){}
        InsuranceWorkAreaJPanel bill = new InsuranceWorkAreaJPanel(userProcessContainer, user, ecoSystem);
        userProcessContainer.add("Insurance main", bill);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_aprvBtnActionPerformed

    private void rjctBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rjctBtnActionPerformed
        // TODO add your handling code here:
        patient.setpInsuranceStatus("Rejected");
        InsuranceWorkAreaJPanel bill = new InsuranceWorkAreaJPanel(userProcessContainer, user, ecoSystem);
        userProcessContainer.add("Insurance main", bill);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_rjctBtnActionPerformed

    private void verificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificationBtnActionPerformed
        // TODO add your handling code here:
        if(patient.getpPoliceStatus().equals("Verifying")||patient.getpPoliceStatus().equals("Verified")||patient.getpPoliceStatus().equals("Rejected")){
            JOptionPane.showMessageDialog(null, "Already verifying/Verified.");
        }
        else{
            patient.setpPoliceStatus("Verifying");
            ecoSystem.getCop().addtoRecord(patient);
            txtpVerification.setText(patient.getpPoliceStatus());
        }
    }//GEN-LAST:event_verificationBtnActionPerformed

    private void txtpVerificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpVerificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpVerificationActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        //patient.setInsuranceStatus("Approved");
        InsuranceWorkAreaJPanel bill = new InsuranceWorkAreaJPanel(userProcessContainer, user, ecoSystem);
        userProcessContainer.add("Insurance main", bill);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aprvBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblpAddress;
    private javax.swing.JLabel lblpAge;
    private javax.swing.JLabel lblpFirstName;
    private javax.swing.JLabel lblpGender;
    private javax.swing.JLabel lblpHealthInsuranceID;
    private javax.swing.JLabel lblpLastName;
    private javax.swing.JLabel lblpPhone;
    private javax.swing.JLabel lblpVerification;
    private javax.swing.JButton rjctBtn;
    private javax.swing.JTable table1;
    private javax.swing.JTextField txtpAddress;
    private javax.swing.JTextField txtpAge;
    private javax.swing.JTextField txtpFirstName;
    private javax.swing.JTextField txtpGender;
    private javax.swing.JTextField txtpLastName;
    private javax.swing.JTextField txtpNumber;
    private javax.swing.JTextField txtpVerification;
    private javax.swing.JTextField txtphInsuranceID;
    private javax.swing.JButton verificationBtn;
    // End of variables declaration//GEN-END:variables
}
