/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.InsuranceAuthority;

import Model.EcoModel;
import Model.Patient.Patient;
import Model.User.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author devikaboddu
 */
public class InsurancePastCustomersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsurancePastCustomersJPanel
     */
    private final JPanel userProcessContainer;
    private final EcoModel ecoSystem;
    User userAccount;
    public InsurancePastCustomersJPanel(JPanel userProcessContainer, User account, EcoModel system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = system;
        this.userAccount = account;
        
        populatePatientTable1();
        
    }
          
private void populatePatientTable1() {
        DefaultTableModel model = (DefaultTableModel) patientTable.getModel();

        model.setRowCount(0);

        for (Patient patient : ecoSystem.getInsuranceDirectory().getInsuranceRecord()) {

            Object[] row = new Object[7];
            row[0] = patient.getpFirstName();
            row[1] = patient.getpLastName();
            row[2] = Float.toString(ecoSystem.getPatDirectory().billTotal(patient));
            row[3] = patient.getpHealthInsuranceID();
            row[6] = patient.getpInsuranceStatus();
            row[5] = patient.getpPoliceStatus();
            row[4] = patient.getpEmailAddress();
            row[5] = patient;
            if(!patient.getpInsuranceStatus().equals("Verifying Insurance")){
            model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();
        viewDtlsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(9, 145, 143));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insurer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 170, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 1400, 10));

        patientTable.getTableHeader().setFont(new java.awt.Font("Trebuchet MS", 1, 16));
        patientTable.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last", "Bill Total", "HealthId", "Email", "Police Verification", "Insurance Status", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(patientTable);
        if (patientTable.getColumnModel().getColumnCount() > 0) {
            patientTable.getColumnModel().getColumn(7).setMinWidth(0);
            patientTable.getColumnModel().getColumn(7).setPreferredWidth(0);
            patientTable.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 990, 200));

        viewDtlsBtn.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        viewDtlsBtn.setForeground(new java.awt.Color(9, 145, 143));
        viewDtlsBtn.setText("View Details");
        viewDtlsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDtlsBtnActionPerformed(evt);
            }
        });
        add(viewDtlsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, 180, 50));

        backBtn.setFont(new java.awt.Font("Menlo", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(9, 145, 143));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/Insurer_40x40.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDtlsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDtlsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = patientTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{

            Patient d = (Patient) patientTable.getValueAt(selectedRow, 5);
            //d.get
            InsurancePastCustomerInfoJPanel bill = new InsurancePastCustomerInfoJPanel(userProcessContainer,ecoSystem, d, userAccount);
            userProcessContainer.add("Past Customer", bill);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);

        }
    }//GEN-LAST:event_viewDtlsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        //patient.setInsuranceStatus("Approved");
        InsuranceWorkAreaJPanel bill = new InsuranceWorkAreaJPanel(userProcessContainer, userAccount, ecoSystem);
        userProcessContainer.add("Insurance main", bill);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable patientTable;
    private javax.swing.JButton viewDtlsBtn;
    // End of variables declaration//GEN-END:variables
}
