/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Doctor;

import Model.Patient.Patient;
import Model.EcoModel;
import Model.User.User;
import Model.Patient.PatientBills;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.CardLayout;

/**
 *
 * @author ramya
 */
public class DocTreatPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DocTreatPatient
     */
    private JPanel userProcessArea;
    private EcoModel ecoModel;
    private User userAccount;
    private Patient patient;
    
    public DocTreatPatientJPanel(JPanel userArea, User myUserAccount, EcoModel myEcoModel, Patient currentPatient) {
        initComponents();
        this.userProcessArea = userArea;
        this.ecoModel = myEcoModel;
        this.userAccount = myUserAccount;
        this.patient = currentPatient;
        populatePatientTable();
    }

    private void populatePatientTable() {
        DefaultTableModel model = (DefaultTableModel) BillTable.getModel();

        model.setRowCount(0);

//        for (Patient_Bills bill : patient.getpBills()) {
//
//            Object[] row = new Object[7];
//            row[0] = bill.getName();
//            row[1] = bill.getOrgType();
//            row[2] = bill.getAmount();
//            row[3] = bill.getStatus();
//            row[4] = bill.getResult();
//            
//            model.addRow(row);
//
//        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        BillTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lblPatientTreatArea = new javax.swing.JLabel();
        btnDischargePatient = new javax.swing.JButton();
        btnEndPatientVisit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnOrderLabReport = new javax.swing.JButton();
        btnRequestMedicine = new javax.swing.JButton();
        btnOrderBloodReport = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 102));

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BillTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        BillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Name", "Organization", "Amount", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BillTable.setPreferredSize(new java.awt.Dimension(300, 80));
        jScrollPane1.setViewportView(BillTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 1030, 191));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 126, 1030, 10));

        lblPatientTreatArea.setBackground(new java.awt.Color(0, 153, 204));
        lblPatientTreatArea.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        lblPatientTreatArea.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientTreatArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientTreatArea.setText("Patient History");
        jPanel1.add(lblPatientTreatArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 320, 50));

        btnDischargePatient.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnDischargePatient.setForeground(new java.awt.Color(0, 0, 102));
        btnDischargePatient.setText("Ready to Discharge");
        btnDischargePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDischargePatientActionPerformed(evt);
            }
        });
        jPanel1.add(btnDischargePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, 210, 40));

        btnEndPatientVisit.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnEndPatientVisit.setForeground(new java.awt.Color(0, 0, 102));
        btnEndPatientVisit.setText("End Visit");
        btnEndPatientVisit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndPatientVisitActionPerformed(evt);
            }
        });
        jPanel1.add(btnEndPatientVisit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 120, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/pat_hist.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 50, 50));

        btnOrderLabReport.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnOrderLabReport.setForeground(new java.awt.Color(0, 0, 102));
        btnOrderLabReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/blood_test_40x40.png"))); // NOI18N
        btnOrderLabReport.setText("Order Lab Test");
        btnOrderLabReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderLabReportActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrderLabReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, 50));

        btnRequestMedicine.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnRequestMedicine.setForeground(new java.awt.Color(0, 0, 102));
        btnRequestMedicine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/med.png"))); // NOI18N
        btnRequestMedicine.setText("Request Medicines");
        btnRequestMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMedicineActionPerformed(evt);
            }
        });
        jPanel1.add(btnRequestMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 370, 250, 50));

        btnOrderBloodReport.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnOrderBloodReport.setForeground(new java.awt.Color(0, 0, 102));
        btnOrderBloodReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/lab_report.png"))); // NOI18N
        btnOrderBloodReport.setText("Order Blood Report");
        btnOrderBloodReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderBloodReportActionPerformed(evt);
            }
        });
        jPanel1.add(btnOrderBloodReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDischargePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDischargePatientActionPerformed
        // TODO add your handling code here:
        patient.setpStatus("Ready to Discharge");
        DocWorkAreaJPanel doctor = new DocWorkAreaJPanel(userProcessArea,userAccount,ecoModel);
        userProcessArea.add("Request Blood", doctor);
        CardLayout layout = (CardLayout) userProcessArea.getLayout();
        layout.next(userProcessArea);
    }//GEN-LAST:event_btnDischargePatientActionPerformed

    private void btnEndPatientVisitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndPatientVisitActionPerformed
        // TODO add your handling code here:
        patient.setpStatus("Under Observation");
        DocWorkAreaJPanel doctor = new DocWorkAreaJPanel(userProcessArea,userAccount,ecoModel);
        userProcessArea.add("Request Blood", doctor);
        CardLayout layout = (CardLayout) userProcessArea.getLayout();
        layout.next(userProcessArea);
    }//GEN-LAST:event_btnEndPatientVisitActionPerformed

    private void btnOrderLabReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderLabReportActionPerformed
        // TODO add your handling code here:

        DocLabReportOrderJPanel docRequestLabTestJPanel = new DocLabReportOrderJPanel(userProcessArea, userAccount, ecoModel, patient);
        userProcessArea.add("Request Lab Tests", docRequestLabTestJPanel);
        CardLayout layout = (CardLayout) userProcessArea.getLayout();
        layout.next(userProcessArea);
    }//GEN-LAST:event_btnOrderLabReportActionPerformed

    private void btnRequestMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMedicineActionPerformed
        // TODO add your handling code here:

        DocMedicineRequestJPanel docMedicineRequestJPanel = new DocMedicineRequestJPanel(userProcessArea, userAccount, ecoModel, patient);
        userProcessArea.add("Request  Medicine", docMedicineRequestJPanel);
        CardLayout layout = (CardLayout) userProcessArea.getLayout();
        layout.next(userProcessArea);
    }//GEN-LAST:event_btnRequestMedicineActionPerformed

    private void btnOrderBloodReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderBloodReportActionPerformed
        // TODO add your handling code here:

        DocBloodReportOrderJPanel docBloodRequestJPanel = new DocBloodReportOrderJPanel(userProcessArea, userAccount, ecoModel, patient);
        userProcessArea.add("Request Blood", docBloodRequestJPanel);
        CardLayout layout = (CardLayout) userProcessArea.getLayout();
        layout.next(userProcessArea);
    }//GEN-LAST:event_btnOrderBloodReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BillTable;
    private javax.swing.JButton btnDischargePatient;
    private javax.swing.JButton btnEndPatientVisit;
    private javax.swing.JButton btnOrderBloodReport;
    private javax.swing.JButton btnOrderLabReport;
    private javax.swing.JButton btnRequestMedicine;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPatientTreatArea;
    // End of variables declaration//GEN-END:variables
}
