/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Pharmacy;

import Model.User.User;
import java.awt.CardLayout;
import Model.Pharmacy.Prescription;
import Model.EcoModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Patient.Patient;
import javax.swing.JPanel;

/**
 *
 * @author devikaboddu
 */
public class PharmacyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyWorkAreaJPanel
     */
    JPanel userWorkArea;
    EcoModel ecoModel;
    User userAccount;
    Prescription med;
    public PharmacyJPanel(JPanel userProcessContainer, User account, EcoModel ecoBusinessModel) {
        initComponents();
        this.userWorkArea = userProcessContainer;
        this.ecoModel = ecoBusinessModel;
        this.userAccount = account;
        populatePatientDetailsTable();
        populatePatientTable1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        btnViewRequest1 = new javax.swing.JButton();
        btnUpdateInventory1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tablePatientDetails1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablePatient1 = new javax.swing.JTable();
        btnView1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblPharmWorkArea1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(128, 206, 206));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1221, 10));

        btnViewRequest1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnViewRequest1.setForeground(new java.awt.Color(128, 206, 206));
        btnViewRequest1.setText("View Request");
        btnViewRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequest1ActionPerformed(evt);
            }
        });
        add(btnViewRequest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, 130, 30));

        btnUpdateInventory1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnUpdateInventory1.setForeground(new java.awt.Color(128, 206, 206));
        btnUpdateInventory1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/refresh.png"))); // NOI18N
        btnUpdateInventory1.setText("Update Inventory");
        btnUpdateInventory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateInventory1ActionPerformed(evt);
            }
        });
        add(btnUpdateInventory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 240, -1, 41));

        tablePatientDetails1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tablePatientDetails1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First", "Last", "PharmaStatus", "HealthId", "Age", "Address", "Email", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tablePatientDetails1);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 840, 195));

        tablePatient1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tablePatient1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First", "Last", "PharmaStatus", "HealthId", "Age", "Address", "Email", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tablePatient1);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 840, 191));

        btnView1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnView1.setForeground(new java.awt.Color(128, 206, 206));
        btnView1.setText("View Request");
        btnView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView1ActionPerformed(evt);
            }
        });
        add(btnView1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, -1, 30));

        jPanel2.setBackground(new java.awt.Color(9, 145, 143));

        lblPharmWorkArea1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        lblPharmWorkArea1.setForeground(new java.awt.Color(255, 255, 255));
        lblPharmWorkArea1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPharmWorkArea1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/pharmacy.png"))); // NOI18N
        lblPharmWorkArea1.setText("Pharmacy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(449, 449, 449)
                .addComponent(lblPharmWorkArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPharmWorkArea1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PREVIOUS REQUESTS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NEW REQUEST");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/people-in-pharmacy-vector.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 680, -1, 80));
    }// </editor-fold>//GEN-END:initComponents

    private void populatePatientTable1() {
        DefaultTableModel model = (DefaultTableModel) tablePatient1.getModel();

        model.setRowCount(0);

        for (Patient patient : ecoModel.getPharmacy().getPatientRecordList()) {

            Object[] row = new Object[8];
            row[0] = patient.getpFirstName();
            row[1] = patient.getpLastName();
            row[2] = patient.getpPharmaStatus();
            row[3] = patient.getpHealthInsuranceID();
            row[4] = patient.getpAge();
            row[5] = patient.getpAddress();
            row[6] = patient.getpEmailAddress();
            row[7] = patient;
           if(patient.getpPharmaStatus().equals("Delivered")){
            model.addRow(row);
           }
        }
    }
    
    private void populatePatientDetailsTable() {
        DefaultTableModel model = (DefaultTableModel) tablePatientDetails1.getModel();

        model.setRowCount(0);

        for (Patient patient : ecoModel.getPharmacy().getPatientRecordList()) {

            Object[] row = new Object[8];
            row[0] = patient.getpFirstName();
            row[1] = patient.getpLastName();
            row[2] = patient.getpPharmaStatus();
            row[3] = patient.getpHealthInsuranceID();
            row[4] = patient.getpAge();
            row[5] = patient.getpAddress();
            row[6] = patient.getpEmailAddress();
            row[7] = patient;
           if(patient.getpPharmaStatus().equals("Requested")){
            model.addRow(row);
           }
        }
    }
    
    private void btnViewRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewRequest1ActionPerformed

    private void btnUpdateInventory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateInventory1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateInventory1ActionPerformed

    private void btnView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnView1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateInventory1;
    private javax.swing.JButton btnView1;
    private javax.swing.JButton btnViewRequest1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblPharmWorkArea1;
    private javax.swing.JTable tablePatient1;
    private javax.swing.JTable tablePatientDetails1;
    // End of variables declaration//GEN-END:variables
}
