/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Pharmacy;

import javax.swing.JPanel;
import Model.User.User;
import Model.Patient.Patient;
import Model.EcoModel;
import java.awt.CardLayout;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.util.regex.Matcher;
import javax.swing.table.DefaultTableModel;
import Model.Pharmacy.Prescription;
/**
 *
 * @author devikaboddu
 */
public class PharmacyCRUDdetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PharmacyCRUDdetailsJPanel
     */
    JPanel userworkArea;
    EcoModel ecoModel;
    User userAccount;
    Prescription med;
    public PharmacyCRUDdetailsJPanel(JPanel userArea, User account, EcoModel ecoBusinessModel) {
        initComponents();
        this.ecoModel = ecoBusinessModel;
        this.userworkArea = userArea;
        this.userAccount = account;
        populateMedicineDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPharm = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAddMedicine = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMedDetails = new javax.swing.JTable();
        lblMedCost = new javax.swing.JLabel();
        txtMedCost = new javax.swing.JTextField();
        txtMedUsage = new javax.swing.JTextField();
        txtMedName = new javax.swing.JTextField();
        lblMedName = new javax.swing.JLabel();
        lblMedUsage = new javax.swing.JLabel();
        txtMedQuantity = new javax.swing.JTextField();
        lblMedQuantity = new javax.swing.JLabel();
        btnDeleteMed = new javax.swing.JButton();
        btnSaveUpdatedMed = new javax.swing.JButton();
        btnMedUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnPharmBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPharm.setBackground(new java.awt.Color(0, 153, 204));
        lblPharm.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        lblPharm.setForeground(new java.awt.Color(255, 255, 255));
        lblPharm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPharm.setText("Pharmacy");
        jPanel1.add(lblPharm, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 220, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 1328, 10));

        btnAddMedicine.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnAddMedicine.setForeground(new java.awt.Color(0, 153, 204));
        btnAddMedicine.setText("Add Medicine");
        btnAddMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedicineActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddMedicine, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 180, 30));

        tableMedDetails.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tableMedDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Med Name", "Med Usage", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableMedDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 788, 186));

        lblMedCost.setBackground(new java.awt.Color(0, 0, 0));
        lblMedCost.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblMedCost.setForeground(new java.awt.Color(255, 255, 255));
        lblMedCost.setText("Cost");
        jPanel1.add(lblMedCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, -1, 30));

        txtMedCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedCostKeyReleased(evt);
            }
        });
        jPanel1.add(txtMedCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 144, 30));
        jPanel1.add(txtMedUsage, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 144, 30));
        jPanel1.add(txtMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 144, 30));

        lblMedName.setBackground(new java.awt.Color(0, 0, 0));
        lblMedName.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblMedName.setForeground(new java.awt.Color(255, 255, 255));
        lblMedName.setText("Medicine Name");
        jPanel1.add(lblMedName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, 30));

        lblMedUsage.setBackground(new java.awt.Color(0, 0, 0));
        lblMedUsage.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblMedUsage.setForeground(new java.awt.Color(255, 255, 255));
        lblMedUsage.setText("Medicine Usage");
        jPanel1.add(lblMedUsage, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, -1, 30));

        txtMedQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMedQuantityKeyReleased(evt);
            }
        });
        jPanel1.add(txtMedQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 144, 30));

        lblMedQuantity.setBackground(new java.awt.Color(0, 0, 0));
        lblMedQuantity.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        lblMedQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblMedQuantity.setText("Quantity");
        jPanel1.add(lblMedQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, 30));

        btnDeleteMed.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnDeleteMed.setForeground(new java.awt.Color(0, 153, 204));
        btnDeleteMed.setText("Delete");
        btnDeleteMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMedActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 100, 30));

        btnSaveUpdatedMed.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnSaveUpdatedMed.setForeground(new java.awt.Color(0, 153, 204));
        btnSaveUpdatedMed.setText("Save Update");
        btnSaveUpdatedMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUpdatedMedActionPerformed(evt);
            }
        });
        jPanel1.add(btnSaveUpdatedMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 160, 30));

        btnMedUpdate.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        btnMedUpdate.setForeground(new java.awt.Color(0, 153, 204));
        btnMedUpdate.setText("Update");
        btnMedUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnMedUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 120, 30));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 213, 32));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 213, 32));

        btnPharmBack.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        btnPharmBack.setForeground(new java.awt.Color(0, 153, 204));
        btnPharmBack.setText("Back");
        btnPharmBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPharmBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnPharmBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/people-in-pharmacy-vector.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1326, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void populateMedicineDetails() {
        DefaultTableModel model = (DefaultTableModel) tableMedDetails.getModel();

        model.setRowCount(0);

        for (Prescription t : ecoModel.getPharmacy().getPrescriptionList()) {
                Object[] row = new Object[4];                
                row[0] = t;
                row[1] = t.getMedUsage();
                row[2] =t.getMedQuantity();
                row[3] = t.getMedPrice();
                model.addRow(row);
        }
    }
    
    private void btnAddMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedicineActionPerformed

        if (txtMedName.getText().equals("") || txtMedUsage.getText().equals("")|| txtMedCost.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the details");
        } else {
            Prescription m = new Prescription();
            m.setName(txtMedName.getText());
            m.setMedQuantity(Integer.parseInt(txtMedQuantity.getText()));
            m.setMedUsage(txtMedUsage.getText());
            m.setMedPrice(Integer.parseInt(txtMedCost.getText()));
            ecoModel.getPharmacy().createPrescription(m);
            populateMedicineDetails();

        }

        txtMedName.setText("");
        txtMedUsage.setText("");
        txtMedCost.setText("");
        txtMedQuantity.setText("");
    }//GEN-LAST:event_btnAddMedicineActionPerformed

    private void txtMedCostKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedCostKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtMedCost.getText());
        if (!match.matches() )
        {
            jLabel3.setText("Please input correct data. HINT: number");
        }
        else
        {
            jLabel3.setText(null);
        }
    }//GEN-LAST:event_txtMedCostKeyReleased

    private void txtMedQuantityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedQuantityKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtMedQuantity.getText());
        if (!match.matches() )
        {
            jLabel2.setText("Please input correct data. HINT: number");
        } else
        {
            jLabel2.setText(null);
        }
    }//GEN-LAST:event_txtMedQuantityKeyReleased

    private void btnDeleteMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMedActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableMedDetails.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Delete Medicine: "+tableMedDetails.getValueAt(selectedRow, 0)+" ??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Prescription p = (Prescription) tableMedDetails.getValueAt(selectedRow, 0);
                ecoModel.getPharmacy().deletePrescription(p);
                populateMedicineDetails();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Select a Customer to delete!");
        }
    }//GEN-LAST:event_btnDeleteMedActionPerformed

    private void btnSaveUpdatedMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUpdatedMedActionPerformed
        // TODO add your handling code here:
        String name = txtMedName.getText();
        String uname=txtMedUsage.getText();
        String password=txtMedCost.getText();
        String quantity= txtMedQuantity.getText();
        if(name.equalsIgnoreCase("")||uname.equalsIgnoreCase("")||password.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Pls, Fill data Correctly!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            ecoModel.getPharmacy().updatePrescription(med,name,uname,Integer.parseInt(password),Integer.parseInt(quantity));
            populateMedicineDetails();
        }
        txtMedName.setText("");
        txtMedUsage.setText("");
        txtMedCost.setText("");
        txtMedQuantity.setText("");
    }//GEN-LAST:event_btnSaveUpdatedMedActionPerformed

    private void btnMedUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableMedDetails.getSelectedRow();
        //Tests p = (Tests) tableTests.getValueAt(selectedRow, 0);
        if(selectedRow>=0){
            med = (Prescription) tableMedDetails.getValueAt(selectedRow, 0);
            txtMedName.setText(med.getName());
            txtMedUsage.setText(med.getMedUsage());
            txtMedCost.setText(Integer.toString(med.getMedPrice()));
            txtMedQuantity.setText(Integer.toString(med.getMedQuantity()));
            // system.getUserAccountDirectory().deleteUserAccount(user);

        }
        else {
            JOptionPane.showMessageDialog(null,"Please select a row");
        }
    }//GEN-LAST:event_btnMedUpdateActionPerformed

    private void btnPharmBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPharmBackActionPerformed
        // TODO add your handling code here:
        //patient.setInsuranceStatus("Approved");
        PharmacyWorkAreaJPanel bill = new PharmacyWorkAreaJPanel(userworkArea, userAccount, ecoModel);
        userworkArea.add("Insurance main", bill);
        CardLayout layout = (CardLayout) userworkArea.getLayout();
        layout.next(userworkArea);
    }//GEN-LAST:event_btnPharmBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMedicine;
    private javax.swing.JButton btnDeleteMed;
    private javax.swing.JButton btnMedUpdate;
    private javax.swing.JButton btnPharmBack;
    private javax.swing.JButton btnSaveUpdatedMed;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblMedCost;
    private javax.swing.JLabel lblMedName;
    private javax.swing.JLabel lblMedQuantity;
    private javax.swing.JLabel lblMedUsage;
    private javax.swing.JLabel lblPharm;
    private javax.swing.JTable tableMedDetails;
    private javax.swing.JTextField txtMedCost;
    private javax.swing.JTextField txtMedName;
    private javax.swing.JTextField txtMedQuantity;
    private javax.swing.JTextField txtMedUsage;
    // End of variables declaration//GEN-END:variables
}
