/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import java.awt.CardLayout;
import Model.DBUtil.DBUtil;
import Model.EcoModel;
import Model.Roles.DoctorAdmin;
import Model.Roles.DoctorUser;
import Model.User.User;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import Model.Pharmacy.Pharmacy;
import Model.Ambulance.Ambulance;
//import Model.BloodDonationCenter.BloodDonationCenter;
import Model.Roles.AmbulanceDriver;
import Model.Roles.Cop;
import Model.Roles.BloodDonationCenter;
import Model.Roles.InsuranceAuthority;

import Model.Roles.Laboratory;
import Model.Roles.PharmacistRole;
import Model.Roles.ReceptionistRole;
/** 
 *
 * @author ramya
 */
public class MainJFrame extends javax.swing.JFrame {
    private final DBUtil dBUtil = DBUtil.getInstance();
    private final EcoModel system;
    /**
     * Creates new form NewJFrame
     */
    public MainJFrame() {
        initComponents();
        system = dBUtil.retrieveSystem();
        this.setSize(1300, 900);
        system.getUserDirectory().createUser("doctor", "doctor", null, new DoctorUser());
        system.getUserDirectory().createUser("docadmin", "docadmin", null, new DoctorAdmin());
        system.getUserDirectory().createUser("ambulance", "ambulance", null, new AmbulanceDriver());
        system.getUserDirectory().createUser("police", "police", null, new Cop());
        system.getUserDirectory().createUser("bloodbank", "bloodbank", null, new BloodDonationCenter());
        system.getUserDirectory().createUser("lab", "lab", null, new Laboratory());   
        system.getUserDirectory().createUser("insurance", "insurance", null, new InsuranceAuthority());
        system.getUserDirectory().createUser("reception", "reception", null, new ReceptionistRole());
        system.getUserDirectory().createUser("pharmacy", "pharmacy", null, new PharmacistRole());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        leftContainer = new javax.swing.JPanel();
        signInBtn = new javax.swing.JButton();
        userNameInputField = new javax.swing.JTextField();
        passwordInputField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginJLabel1 = new javax.swing.JLabel();
        signOutBtn = new javax.swing.JButton();
        appLogo1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mainContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        homeDisplay1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftContainer.setBackground(new java.awt.Color(128, 206, 206));
        leftContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signInBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        signInBtn.setForeground(new java.awt.Color(9, 145, 143));
        signInBtn.setText("Login");
        signInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInBtnActionPerformed(evt);
            }
        });
        leftContainer.add(signInBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 120, 35));

        userNameInputField.setFont(new java.awt.Font("Noto Sans Kannada", 2, 14)); // NOI18N
        userNameInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameInputFieldActionPerformed(evt);
            }
        });
        leftContainer.add(userNameInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 35));

        passwordInputField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordInputFieldActionPerformed(evt);
            }
        });
        leftContainer.add(passwordInputField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 150, 35));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        leftContainer.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        leftContainer.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 108, -1));
        leftContainer.add(loginJLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 231, -1, -1));

        signOutBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        signOutBtn.setForeground(new java.awt.Color(9, 145, 143));
        signOutBtn.setText("Logout");
        signOutBtn.setEnabled(false);
        signOutBtn.setFocusCycleRoot(true);
        signOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutBtnActionPerformed(evt);
            }
        });
        leftContainer.add(signOutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 35));

        appLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/logo_130x130.png"))); // NOI18N
        leftContainer.add(appLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, 130));
        leftContainer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 50, 40));

        jSplitPane2.setLeftComponent(leftContainer);

        mainContainer.setBackground(new java.awt.Color(255, 255, 255));
        mainContainer.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        homeDisplay1.setBackground(new java.awt.Color(255, 255, 255));
        homeDisplay1.setForeground(new java.awt.Color(255, 255, 255));
        homeDisplay1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeDisplay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/assets/hospital.gif"))); // NOI18N
        homeDisplay1.setMaximumSize(new java.awt.Dimension(1295, 950));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(9, 145, 143));
        jLabel3.setText("HOSPITAL MANAGEMENT");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(homeDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homeDisplay1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );

        mainContainer.add(jPanel1, "card3");

        jSplitPane2.setRightComponent(mainContainer);

        getContentPane().add(jSplitPane2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInBtnActionPerformed
        try{
            User ua = system.getUserAccountDirectory().userAuthorization(userNameInputField.getText(), passwordInputField.getText());
            CardLayout layout = (CardLayout) mainContainer.getLayout();
            System.out.println("role of user ---"+ua.getUserRole());
            mainContainer.add(ua.getUserRole().createWorkArea(mainContainer, ua, system));
            layout.next(mainContainer);
            signOutBtn.setEnabled(true);
        }
        catch(Exception e){
            System.out.println("exception ---");
            //e.printStackTrace();
            System.out.println("exception due to ---"+e.getMessage());
            JOptionPane.showMessageDialog(null,"Username/Password is wrong!","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_signInBtnActionPerformed

    private void userNameInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameInputFieldActionPerformed

    private void passwordInputFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordInputFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordInputFieldActionPerformed

    private void signOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutBtnActionPerformed
        signOutBtn.setEnabled(false);
        userNameInputField.setEnabled(true);
        passwordInputField.setEnabled(true);
        signInBtn.setEnabled(true);
        userNameInputField.setText("");
        passwordInputField.setText("");

        Logout ua = new Logout(mainContainer);
        mainContainer.add("logout", ua);
        CardLayout layout = (CardLayout) mainContainer.getLayout();
        layout.next(mainContainer);
        dBUtil.storeSystem(system);

    }//GEN-LAST:event_signOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appLogo1;
    private javax.swing.JLabel homeDisplay1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel leftContainer;
    private javax.swing.JLabel loginJLabel1;
    private javax.swing.JPanel mainContainer;
    private javax.swing.JPasswordField passwordInputField;
    private javax.swing.JButton signInBtn;
    private javax.swing.JButton signOutBtn;
    private javax.swing.JTextField userNameInputField;
    // End of variables declaration//GEN-END:variables
}
//Login
//try{
//            User user = system.getUserAccountDirectory().userAuthorization(txtUserNameInput.getText(), pwdInput.getText());
//            CardLayout layout = (CardLayout) panelWorkArea.getLayout();
//            System.out.println("Hello from main j frame");
//            System.out.println("role of user ---"+user.getUserRole());
//            panelWorkArea.add(user.getUserRole().createWorkArea(panelWorkArea, user, system));
//            layout.next(panelWorkArea);
//            btnLogout.setEnabled(true);
//        }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(null,"Username/Password is wrong!","Warning",JOptionPane.WARNING_MESSAGE);
//        }
//}

//Logout
//btnLogout.setEnabled(false);
//        txtUserNameInput.setEnabled(true);
//        pwdInput.setEnabled(true);
//        btnLogin.setEnabled(true);
//        txtUserNameInput.setText("");
//        pwdInput.setText("");
//
//        Logout ua = new Logout(panelWorkArea);
//        panelWorkArea.add("logout", ua);
//        CardLayout layout = (CardLayout) panelWorkArea.getLayout();
//        layout.next(panelWorkArea);
//        dBUtil.storeSystem(system);