/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Utils;

import Model.Ambulance.Ambulance;
import Model.EcoModel;
import Model.Patient.Patient;
import Model.User.User;
import UI.Ambulance.ReceptionAmbulanceWorkAreaJPanel;
import com.kingaspx.util.BrowserUtil;
import com.kingaspx.version.Version;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.dom.By;
import com.teamdev.jxbrowser.chromium.dom.DOMDocument;
import com.teamdev.jxbrowser.chromium.dom.DOMElement;
import com.teamdev.jxbrowser.chromium.dom.DOMInputElement;
import com.teamdev.jxbrowser.chromium.events.ConsoleEvent;
import com.teamdev.jxbrowser.chromium.events.FinishLoadingEvent;
import com.teamdev.jxbrowser.chromium.events.LoadAdapter;
import com.teamdev.jxbrowser.chromium.events.TitleEvent;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JPanel;

/**
 *
 * @author ramya
 */
public class GoogleMapsJPanel extends javax.swing.JPanel {
    Browser jxBrowser;
    BrowserView jxBrowserView;
    private final EcoModel system;
    private final JPanel userProcessContainer;
    User userAccount;        
    private final Ambulance ambulance;
    private final Patient patient;
    String accidentLocation;
    
    private void open_site() throws FileNotFoundException, IOException {        
        BrowserUtil.setVersion(Version.V6_22);
        jxBrowser = new Browser();
        jxBrowserView = new BrowserView(jxBrowser);
        Map_JPanel.add(jxBrowserView, BorderLayout.CENTER);
        jxBrowser.addTitleListener((TitleEvent evt) -> {
            lblMapsHeading.setText("   " + evt.getTitle());
        });
        jxBrowser.addConsoleListener((ConsoleEvent evt) -> {
            System.out.println("LOG: " + evt.getMessage());
        });
        jxBrowser.addLoadListener(new LoadAdapter() {
            @Override
            public void onFinishLoadingFrame(FinishLoadingEvent evt) {
                evt.getBrowser().setZoomLevel(-2);
            }
        });
        
        File file = new File("\\Users\\ritvik\\NetBeansProject\\Final/AED_FinalProject\\simple_map.html");
        BufferedReader reader = new BufferedReader(new FileReader(file));
        StringBuilder stringBuilder = new StringBuilder();
        String line = null;
        String ls = System.getProperty("line.separator");
        while ((line = reader.readLine()) != null) {
                stringBuilder.append(line);
                stringBuilder.append(ls);
        }

        stringBuilder.deleteCharAt(stringBuilder.length() - 1);
        reader.close();
        jxBrowser.loadHTML(stringBuilder.toString());
//      Test if loading url on JXBrowser works
//      jxBrowser.loadURL("https://www.google.com");
    }
    
    
    /**
     * Creates new form GoogleMaps
     */
    public GoogleMapsJPanel(JPanel userProcessContainer, EcoModel system,User account, Ambulance ambulance, String accidentLocation) throws FileNotFoundException, IOException {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = system;
        this.ambulance = ambulance;
        this.accidentLocation = accidentLocation;
        this.patient = new Patient();
        open_site();
    }
    
    public GoogleMapsJPanel(JPanel userProcessContainer, EcoModel system,User account, Ambulance ambulance, String accidentLocation, Patient p) throws FileNotFoundException, IOException {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.system = system;
        this.ambulance = ambulance;
        this.accidentLocation = accidentLocation;
        this.patient = p;
        open_site();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Map_JPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        lblMapsHeading = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        Map_JPanel.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        Map_JPanel.setLayout(new java.awt.BorderLayout());
        add(Map_JPanel, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(9, 145, 143));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(9, 145, 143));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 100, 30));

        lblMapsHeading.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        lblMapsHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblMapsHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMapsHeading.setText("Route from driver's location to accident location");
        jPanel2.add(lblMapsHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 770, 50));

        btnBack1.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(9, 145, 143));
        btnBack1.setText("Get Route");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 140, 30));

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        //ReceptionAmbulanceWorkAreaJPanel
        ReceptionAmbulanceWorkAreaJPanel emergencyRegistrationPanel = new ReceptionAmbulanceWorkAreaJPanel(userProcessContainer,system, userAccount,ambulance, this.patient);
        userProcessContainer.add("Patient Bill", emergencyRegistrationPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        DOMDocument doc = jxBrowser.getDocument();
        DOMElement start_element = doc.findElement(By.id("start"));
        DOMElement end_element = doc.findElement(By.id("end"));
        DOMElement btn_element = doc.findElement(By.id("submit"));
        DOMElement button = (DOMElement) btn_element;

        DOMInputElement startLocation = (DOMInputElement) start_element;
        DOMInputElement endLocation = (DOMInputElement) end_element;
        startLocation.setValue("Northeastern University, Boston");
        endLocation.setValue(this.accidentLocation);
        button.click();
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Map_JPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMapsHeading;
    // End of variables declaration//GEN-END:variables
}
